[pytest]
addopts =
    --embedded-services idf,qemu
    --app-path .
    --build-dir build/e2e-pytest
    --qemu-extra-args="-m 8M -nic user,model=open_eth"
markers =
    esp32s3: tests targeting the ESP32-S3 (QEMU)
